[font]
size = 20
normal = { family = "Sarasa Fixed J", style = "Light" }

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
  # This makes ClaudeCode SHIFT+Enter work
  { key = "Return", mods = "Shift", chars = "\n" }
] 
